// Generated by CoffeeScript 1.8.0
var gulp;

gulp = require('gulp');

gulp.task('one', function() {
  return console.log('one');
});

gulp.task('two', function() {
  return console.log('two');
});

gulp.task('default', function() {
  gulp.pipe();
  return console.log('default');
});
